public class EventCommand implements Command{
    // fields
    private String input;

    // constructor
    public EventCommand(String input) {
        this.input = input;
    }

    private static String[] getStrings(String input) {
        String[] sub = input.substring(6).split("\\\\"); // solution to backslash character found using Google search
        if (sub.length != 3) throw new IllegalBotArgumentException("Wrong number of arguments!", input);
        if (!sub[1].startsWith("from")) throw new IllegalBotArgumentException("No 'from' argument!", input);
        if (sub[1].length() < 5) throw new IllegalBotArgumentException("No argument found!", input); // no argument
        if (!sub[2].startsWith("to")) throw new IllegalBotArgumentException("No 'to' argument!", input);
        if (sub[2].length() < 3) throw new IllegalBotArgumentException("No argument found!", input); // no argument
        return sub;
    }

    @Override
    public void execute(TaskList tasks) {
        if (input.length() < 6) throw new IllegalBotArgumentException("No argument found!", input); // no argument

        String[] sub = getStrings(input); // function to group multiple error-catching statements auto-generated by IntelliJ IDEA IDE


        String task = sub[0];
        if (task.isEmpty()) throw new IllegalBotArgumentException("No Task stated:", input);

        String startTime = sub[1].substring(5);
        if (startTime.isEmpty()) throw new IllegalBotArgumentException("No 'from' string stated:", input);
        System.out.println("we got here");
        String endTime = sub[2].substring(3);
        if (endTime.isEmpty()) throw new IllegalBotArgumentException("No 'to' string stated:", input);

        tasks.add(new Event(task, startTime, endTime));
        System.out.println(
                APleaseBot.line +
                        "Got it. I've added this task:\n" +
                        "  " + tasks.get(tasks.getItemCount() - 1).toString() + "\n" +
                        "Now you have " + tasks.getItemCount() + " tasks in the list" + "\n" +
                        APleaseBot.line
        );
    }
}
